Team-MeetGo/MeetGO

src/app/meetingRoom/[id]/page.tsx
src/components/room/MeetingRoom.tsx
src/components/room/participants/AcceptanceRoomButtons.tsx
src/components/room/participants/Member.tsx
src/components/room/participants/RealTimeSubscription.tsx
src/components/room/participants/RoomInformation.tsx
src/hooks/custom/participants.ts
src/hooks/custom/room.ts

closed #19
components/room/participants/Roominformation: 방의 정보를 room_id에서 필터링해 표시합니다.
```
'use client';
import meetingRoomHandler from '(@/hooks/custom/room)';
import { Database } from '(@/types/database.types)';
import { UUID } from 'crypto';
import { useEffect, useState } from 'react';
type MeetingRoomType = Database['public']['Tables']['room']['Row'];
function RoomInformation({ roomId }: { roomId: UUID }) {
const [room, setRoom] = useState<MeetingRoomType[]>();
const { getRoomInformation } = meetingRoomHandler();
const getSingleRoom = async () => {
const singleRoom = await getRoomInformation(roomId);
if (!singleRoom) {
return;
}
setRoom(singleRoom);
};
getSingleRoom();
}, []);
if (!room) return;
const { feature, location, member_number, room_title } = room[0];
return …
```

이혜진 - [feat]: 수락창에 방 정보 나타내기

---

src/app/meetingRoom/[id]/page.tsx
src/components/room/MeetingRoomForm.tsx
src/components/room/participants/AcceptanceRoomButtons.tsx
src/components/room/participants/Member.tsx
src/components/room/participants/RealTimeSubscription.tsx
src/hooks/custom/participants.ts

closed #42 
1. 수락창으로 이동하면 최대 참가인원과 현재 참가인원을 비교합니다.
2. 최대 참가인원이 더 크면 버튼이 비활성화 됩니다.
3. 두 값이 같으면 버튼이 활성화 됩니다.
components/room/participants/AcceptanceRoomButtons: 버튼의 활성화/비활성화를 구현했습니다.
```
'use client';
import participants from '(@/hooks/custom/participants)';
import meetingRoomHandler from '(@/hooks/custom/room)';
import { clientSupabase } from '(@/utils/supabase/client)';
import { useRouter } from 'next/navigation';
import { useEffect, useState } from 'react';
import type { UUID } from 'crypto';
import { Database } from '(@/types/database.types)';
type ParticipantType = Database['public']['Tables']['participants']['Row'];
const AcceptanceRoomButtons = ({ roomId }: { roomId: UUID }) => {
const router = useRouter();
const [maximumParticipants, setMaximumParticipants] = useState(0);
const …
```

이혜진 - [feat/#42] -  수락창의 인원수 달성시 채팅방으로 가는 버튼 활성화

---

src/app/review/pageNumber/[pageNumber]/page.tsx

closed #68 
- review/pageNumber/[pageNumber]/page.tsx
```tsx
const [isLoggedIn, setIsLoggedIn] = useState(false);
const checkLoginStatus = async () => {
const data = await clientSupabase.auth.getUser();
console.log(data.data.user);
if (data.data.user !== null) {
setIsLoggedIn(true);
} else {
setIsLoggedIn(false);
}
};
checkLoginStatus();
}, []);
<div>{isLoggedIn ? <NewReview /> : null}</div>
```
```
```

양유진 - [feat/#68] - 로그인 상태에서만 리뷰 등록 버튼이 보이게 수정

---

src/components/room/MeetingRoomForm.tsx

closed #66 
components/room/MeetingRoomForm: 방 생성하자마자 바로 방으로 이동
```
'use client';
import { useTagStore } from '(@/store/zustand)';
import { clientSupabase } from '(@/utils/supabase/client)';
import { Button, Modal, ModalBody, ModalContent, ModalFooter, ModalHeader, useDisclosure } from '@nextui-org/react';
import { useState } from 'react';
import TagList from './MeetingRoomFeatureTags';
import { userStore } from '(@/store/userStore)';
import type { Database } from '(@/types/database.types)';
import { useRouter } from 'next/navigation';
type NextMeetingRoomType = Database['public']['Tables']['room']['Insert'];
function MeetingRoomForm() {
const router = useRouter();
const { tags, resetTags } = useTagStore();
const { isOpen, onOpen, onOpenChange } = useDisclosure();
const { user } = …
```

이혜진 - feat: 로비창에서 방을 만들면 바로 방으로 이동

---

src/components/room/MeetingRoom.tsx
src/components/room/MeetingRoomForm.tsx
src/components/room/participants/AcceptanceRoomButtons.tsx
src/hooks/custom/room.ts
src/types/database.types.ts

closed #75
components/meetingRoom : 채팅방이 형성된 경우 클릭하면 채팅창으로 이동
```
//채팅창으로 넘어갔을 경우에는 채팅창으로 이동
const { data: alreadyChat } = await clientSupabase
.from('chatting_room')
.select('*')
.eq('room_id', room_id)
.eq('isActive', true);
if (alreadyChat && alreadyChat?.length) {
// 만약 isActive인 채팅방이 이미 있다면 그 방으로 보내기
router.replace(`/chat/${alreadyChat[0].chatting_room_id}`);
}
```
```
```

이혜진 - feat: 채팅방이 형성된 방을 클릭하면 채팅창으로 이동

---

src/components/room/MeetingRoomList.tsx
src/hooks/custom/room.ts

closed #74 
components/room/MeetingRoomList : 유저가 참여하고 있는 방 리스트업
```
'use client';
import meetingRoomHandler from '(@/hooks/custom/room)';
import { useEffect, useState } from 'react';
import MeetingRoom from './MeetingRoom';
import { userStore } from '(@/store/userStore)';
import type { Database, Tables } from '(@/types/database.types)';
function MeetingRoomList() {
type MeetingRoom = Database['public']['Tables']['room']['Row'];
const { user } = userStore((state) => state);
const [meetingRoomList, setMeetingRoomList] = useState<MeetingRoom[]>();
const [myMeetingRoomList, setMyMeetingRoomList] = useState<MeetingRoom[]>();
const [chattingRoomList, setChattingRoomList] = useState<MeetingRoom[]>();
const { getMeetingRoom, getChattingRoom, getMyRoom } = meetingRoomHandler(); …
```

이혜진 - feat/#74: 유저가 참여중인 방 최상단에 위치

---

src/components/room/participants/Member.tsx

closed #80
components/participants/Member: 들어온 사람들의 아이디를 비교해서 방장 추출, 표시
```
const leaderSelector = async () => {
const { data: nowLeader } = await clientSupabase.from('room').select('*').eq('room_id', params.id);
if (!nowLeader || nowLeader === null) return;
setLeaderMember(nowLeader[0].leader_id as string);
};
```
```
```

이혜진 - feat: 방 리더에게 리더 표시하기

---

src/app/page.tsx
src/app/test/page.tsx
src/components/common/NavBar.tsx
src/components/common/SignOut.tsx
src/middleware.ts
src/middleware/chain.ts
src/middleware/checkSchoolMiddleware.ts
src/middleware/middlewareType.ts
src/middleware/routeHandlerMiddleware.ts
src/middleware/schoolValidateMiddleware.ts
src/middleware/updateSessionMiddleware.ts
src/utils/supabase/middleware.ts

미들웨어랑 뒤로가기 막기 작업 중입니다.
redirect 부분 추가할 거 있으면 추가해주세요.
```

황인정 - [Feat]: 미들웨어 작업중 

---

src/components/room/EditMeetingRoom.tsx
src/components/room/MeetingRoom.tsx
src/components/room/MeetingRoomFeatureTags.tsx
src/components/room/MeetingRoomForm.tsx
src/components/room/participants/AcceptanceRoomButtons.tsx
src/components/room/participants/Member.tsx
src/components/room/participants/RoomInformation.tsx
src/store/roomStore.ts
src/types/roomTypes.ts

closed #91
components/room/MeetingRoomFeatureTags: 태그 선택을 다섯개로 제한하기
```
'use client';
import { useTagStore } from '(@/store/roomStore)';
import { favoriteOptions } from '(@/utils/FavoriteData)';
import { Chip, Select, SelectItem } from '@nextui-org/react';
import { useState } from 'react';
const TagList = () => {
const [selected, setSelected] = useState<Set<string>>(new Set([]));
const { setTags, tags } = useTagStore();
const handleSelect = (value: string[]) => {
if (selected.size > 5) {
alert('최대 5개까지 선택 가능합니다.');
return;
}
setSelected(new Set(value));
};
const handleDelete = (value: string) => {
const newSelected = new Set(selected);
newSelected.delete(value);
setSelected(newSelected);
};
const addFavorite = async () => {
const favoriteArray = Array.from(selected);
return …
```

이혜진 - feat: 태그선택 왼쪽정렬로 다섯개 제한하기

---

src/components/room/MeetingRoom.tsx

closed #93
components/room/MeetingRoom: 리더인 경우에만 수정/삭제 권한이 있게 작성하였다.
```
{user[0].user_id === leader_id ? (
<div>
<DeleteMeetingRoom id={room_id} />
<EditMeetingRoom room={room} />
</div>
) : null}
```
조건을 다시 생각해보니 만든 사람이 방에서 나가 리더가 아닌 경우 수정/삭제의 권한이 있으면 안됐다.
리더인 경우에만 수정/삭제 권한이 있도록 기능 구현 방향을 바꿨다.
```
```

이혜진 - feat: 수정/삭제를 방을 만든 사람에게만 보이게

---

src/components/common/NavBar.tsx
src/components/common/NavBarContents.tsx
src/components/user/InitUser.tsx
src/components/user/LoginForm.tsx
src/middleware/chatRouteHandler.ts
src/store/userStore.ts

closed #101
clientSupabase로 getUser 하기
**clientSupabase 사용**
**userStore에 isLoggedIn, setIsLoggedIn 추가**
**LoginForm.tsx 로그인 로직에서 isLoggedIn 상태 true로 변경**
**NavBarContents.tsx 로그아웃 로직에서 isLoggedIn 상태 false로 변경**
**InitUser.tsx 내 useEffect**

황인정 - [feat]: 로그인/로그아웃 시 navBar 상태 즉시 변경

---

src/app/chat/[chatroom_id]/page.tsx
src/components/chat/ChatLoading.tsx
src/components/chat/chatBody/ChatList.tsx
src/components/chat/chatBody/ChatSearch.tsx
src/components/chat/chatHeader/ChatHeader.tsx
src/components/chat/chatHeader/InitChat.tsx
src/components/chat/sidebar/SideBar.tsx
src/components/room/MeetingRoomList.tsx
src/components/user/InitUser.tsx
src/hooks/useQueries/useChattingQuery.ts
src/middleware/chatRouteHandler.ts
src/middleware/routeHandlerMiddleware.ts
src/services/queryFns.ts
src/services/queryKeys.ts
src/store/chatStore.ts
src/utils/constant.ts
src/utils/index.ts

#109 
QueryKey
query-func
커스텀 쿼리훅
사용처
새로고침 시 쿼리 키 관련 에러 => 해결예정

황인정 - [feat]: chat 데이터 react-query로 받아오기

---

src/app/meetingRoom/[id]/page.tsx
src/components/room/MeetingRoomList.tsx
src/components/room/participants/AcceptanceRoomButtons.tsx
src/components/room/participants/Member.tsx
src/components/room/participants/RoomInformation.tsx

closed #113 closed #114
components/room/MeetingRoomList: index를 page와 비교하여 mapping하여 리스트를 구현.
```
'use client';
import meetingRoomHandler from '(@/hooks/custom/room)';
import { useRecruitingMyroomQuery } from '(@/hooks/useQueries/useMeetingQuery)';
import { useEffect, useState } from 'react';
import { IoMdRefresh } from 'react-icons/io';
import MeetingRoom from './MeetingRoom';
import MeetingRoomForm from './MeetingRoomForm';
import type { MeetingRoomType, MeetingRoomTypes } from '(@/types/roomTypes)';
import type { User } from '@supabase/supabase-js';
function MeetingRoomList({ user }: { user: User | null }) {
const [page, setPage] = useState(1);
const result = useRecruitingMyroomQuery(user ? user.id : '');
const recruitingRoom = result[0] as MeetingRoomTypes;
const myRoom = …
```

이혜진 - feat: 내가 참여한 방 화살표로 좌우로 이동, 새로고침 기능

---

src/components/mypage/AvatarForm.tsx
src/components/mypage/Favorite.tsx
src/components/mypage/MetPeople.tsx
src/components/mypage/MyPost.tsx
src/components/mypage/Profile.tsx
src/components/mypage/SchoolForm.tsx
src/hooks/useMutation/useProfileMutation.ts
src/hooks/useQueries/useUserQuery.ts
src/query/user/metPeopleQueryFns.ts
src/types/userTypes.ts

최희라 - [feat] : 학교 인증 모달창으로 변경

---

src/components/chat/sidebar/DateTimePicker.tsx

[fix/#139] invalidate time 오류 수정

---

src/components/chat/sidebar/DateTimePicker.tsx
src/components/chat/sidebar/Map.tsx
src/hooks/useMutation/useMeetingLocationMutation.ts

-  build 오류 해결
```tsx
..
const clearMeetingLocationMutation = useClearMeetingLocationMutation();
...
// 장소 선택 함수
const handleSelectLocation = async (barName: string) => {
setSelectedMeetingLocation(barName);
setIsLocationSelected(!isLocationSelected);
if (!chatRoomId) {
return;
}
if (barName === selectedMeetingLocation) {
try {
await clearMeetingLocationMutation.mutateAsync(chatRoomId);
} catch (error) {
console.error('미팅장소 삭제 오류:', error);
}
} else {
try {
await updateMeetingLocationMutation.mutateAsync({ chatRoomId, barName });
} catch (error) {
console.error('미팅장소 업데이트 오류:', error);
}
}
};
...
```
```
```

신서연 - [Refactor] : build 오류 수정, 리더일때만 선택 

---

src/components/chat/sidebar/DateTimePicker.tsx

```tsx
const meetingTime = new Date(String(chat?.[0]?.meeting_time));
if (meetingTime instanceof Date && !isNaN(meetingTime.getTime())) {
setSelectedMeetingTime(meetingTime);
}
}, [chatRoomId, chat]);
```
```
```

신서연 - [Refactor] : 사이드바 오류 해결

---

src/components/common/NavBarContents.tsx
src/components/room/participants/AcceptanceRoomButtons.tsx
src/components/user/LoginForm.tsx
src/middleware/routeHandlerMiddleware.ts

최희라 - fix : 로그인, 회원가입 주소 변경

---

src/app/chat/[chatroom_id]/page.tsx
src/components/chat/sidebar/DateCustomeInput.tsx
src/components/chat/sidebar/DateTimePicker.tsx
src/components/chat/sidebar/Map.tsx

[style/#139] react-icons 변경

---

src/components/mypage/MetPeople.tsx

최희라 - [fix] : 카카오ID요청 상대프로필사진 이미지 비율맞게 들어오도록 조정

---

src/components/chat/sidebar/DateTimePicker.tsx
src/components/chat/sidebar/Map.tsx

[fix/#139] 날짜 장소 선택

---

src/app/chat/[chatroom_id]/page.tsx
src/app/meetingRoom/(lobby)/page.tsx
src/app/meetingRoom/[id]/page.tsx
src/components/room/DeleteMeetingRoom.tsx
src/components/room/MeetingRoom.tsx
src/components/room/MeetingRoomList.tsx
src/components/room/participants/AcceptanceRoomButtons.tsx
src/components/room/participants/Member.tsx
src/components/room/participants/RoomInformation.tsx
src/hooks/useMutation/useMeetingMutation.ts
src/hooks/useQueries/useMeetingQuery.ts
src/query/meetingRoom/meetingQueryFns.ts

홈페이지 점검 후 개선과 빌드
타입에러 : 같은 UUID를 사용해도 user_id와는 다르게 room_id는 오류를 발생시켰습니다.
모든 room_id를 string으로 변환해도 같은 오류가 발생되어서 다시 UUID로 수정합니다.
수락창 연결 오류 : 컴포넌트에 return값이 있으면 적절하지 않다는 피드백을 받아 수정하였습니다.
함수 안에서의 return은 사용해도 타입 에러가 발생하지 않으니 조건이 필요하다면 if 등으로 바꾸는 것이 좋다는 것을 알았습니다.
모든 조건 항목에 return을 추가하고, 정상작동을 확인하였습니다.
채팅창이 생성되면 채팅창으로 이동, 인원수 확인 등.
```
```

Feat acceptanceroom/#141

---

src/app/page.tsx
src/components/mainpage/getMostLikedReview.tsx

황인정 - [fix]: GetMostLikedReview 컴포넌트 빌드 오류 해결

---

src/components/chat/chatBody/ChatList.tsx
src/components/common/InitChatRealTime.tsx
src/components/room/MeetingRoom.tsx

황인정 - [fix]: 로비페이지에 Chip 빠져나오는 부분 스타일 수정

---

src/components/common/NavBarContents.tsx

최희라 - [Fix] : Logout 버튼 동작 이슈 해결

---

src/components/common/NavBarContents.tsx

최희라 - [fix] : DropdownItem 오류 해결

---

src/components/common/NavBarContents.tsx
src/components/mypage/MetPeople.tsx

최희라 - [style] : 카톡ID요청하기 스타일 수정

---

package.json
src/components/common/NavBarContents.tsx
src/components/mypage/AvatarForm.tsx
src/components/mypage/Profile.tsx
yarn.lock

최희라 - [fix] : 이미지 로딩 오류 해결

---

src/app/mypage/page.tsx
src/app/provider/QueryProvider.tsx
src/components/common/NavBarContents.tsx
src/components/mypage/AvatarForm.tsx
src/components/mypage/Favorite.tsx
src/components/mypage/Profile.tsx
src/components/mypage/ProfileHeader.tsx
src/components/user/JoinForm.tsx
src/components/user/LoginForm.tsx
src/hooks/useMutation/useSchoolMutation.ts
src/hooks/useQueries/useUserQuery.ts
src/query/user/userQueryKeys.ts
src/service/index.ts
src/store/modalStore.ts
src/store/userStore.ts

최희라 - [fix] : 성별 여러번 수정 안되도록 변경, 기타 코드 리팩토링, 프로필 사진 오류 수정

---

src/components/common/NavBarContents.tsx
src/components/mypage/Favorite.tsx

최희라 - [style] : Navbar 스켈레톤 추가, 로그아웃시 강제새로고침, 이상형 스타일 수정

---

src/components/room/lobby/MeetingRoomList.tsx
src/components/room/participants/Member.tsx
src/components/room/singleMeetingRoom/MeetingRoom.tsx
src/service/sidebar/index.ts

이혜진 del: 기능없는 코드 삭제

---

src/components/common/NavBarContents.tsx
src/components/common/customToast.tsx
src/components/mypage/AvatarForm.tsx
src/components/mypage/MetPeople.tsx
src/components/mypage/SchoolForm.tsx
src/hooks/useMutation/useMetPeopleMutation.ts
src/query/review/reviewQueryFns.ts
src/service/index.ts

최희라 - [feat] : 카톡ID 요청 알림창 뜨는 기능 구현

---

src/app/page.tsx
src/components/common/ValidationModal.tsx
src/components/mainpage/ProfileRouteModal.tsx
src/components/mypage/Profile.tsx
src/components/user/LoginForm.tsx
src/hooks/useMutation/useFirstLoginMutation.ts
src/hooks/useQueries/useUserQuery.ts
src/service/index.ts
src/store/modalStore.ts
src/types/database.types.ts
src/types/modalTypes.ts
src/utils/api/authAPI.ts

최희라 - [feat] : 회원탈퇴 기능 및 메인화면에서 프로필 설정을 권유하는 모달창 구현

---

src/components/mypage/Profile.tsx
src/components/mypage/SchoolForm.tsx

최희라 - [style] : 프로필 스타일 수정

---

src/components/room/LobbySkeleton.tsx
src/hooks/useMutation/useMeetingMutation.ts

closed #241
Card 하나를 만들어 붙여넣는 형식으로 만들었다.
```
<Card className="w-[333px] h-[241px] p-6 space-y-5 gap-2" radius="lg">
<Skeleton isLoaded={isLoaded} className="rounded-lg">
<div className="h-[16px] rounded-lg bg-secondary"></div>
</Skeleton>
<Skeleton isLoaded={isLoaded} className="rounded-lg">
<div className="h-[26px] rounded-lg bg-secondary"></div>
</Skeleton>
<div className="space-y-3">
<Skeleton isLoaded={isLoaded} className="w-3/5 rounded-lg">
<div className="h-[16px] w-full rounded-lg bg-secondary"></div>
</Skeleton>
<Skeleton isLoaded={isLoaded} className="w-4/5 rounded-lg">
<div className="h-[16px] w-full rounded-lg bg-secondary-300"></div>
</Skeleton>
<Skeleton isLoaded={isLoaded} className="w-2/5 rounded-lg">
<div className="h-[14px] w-full rounded-lg bg-secondary-200"></div> …
```

이혜진 - [feat] : 로비에 스켈레톤 만들기

---

src/components/chat/sidebar/DateCustomeInput.tsx
src/components/chat/sidebar/DateTimePicker.tsx
src/components/chat/sidebar/Map.tsx
src/components/chat/sidebar/SideBar.tsx

장소 선택시 카드의 변경색 오류 수정했습니다.
새로고침시 유지가 안돼서 useEffect를 만들어서 작동되게 했습니다.
```tsx
...
if (meetingLocation) {
setSelectedMeetingLocation(meetingLocation);
}
}, [meetingLocation]);
...
// 장소 선택 함수
const handleSelectLocation = (barName: string) => {
if (barName === meetingLocation) {
setSelectedMeetingLocation('');
} else {
setSelectedMeetingLocation(barName);
}
updateMeetingLocationMutation.mutate({ chatRoomId, barName });
};
...
```
```
```

신서연 : [Refactor] - alert창, 장소선택 오류 수정

---

package.json
src/components/mypage/Profile.tsx
src/components/mypage/ProfileHeader.tsx
src/components/review/ReviewComment.tsx
src/components/review/ReviewDetail.tsx
src/components/review/ReviewEditModal.tsx
src/components/review/comment/CommentCard.tsx
src/components/user/JoinForm.tsx
src/hooks/useMutation/useReviewMutations.ts
src/hooks/useQueries/useUserQuery.ts
yarn.lock

**반드시 node.modules 폴더를 삭제 후 yarn 재설치 부탁드립니다!**
**삭제 안되고 permitted (권한) 문구 뜨면 yarn cache clean 터미널에 타이핑 후 삭제해주세요!**
```
```
```
```

최희라 - [docs] : nextUI 최신버전 설치

---

src/components/chat/sidebar/SideBar.tsx

황인정: [style/#218] - 반응형 사이드바 너비 수정 w-80 -> w-96

---

src/app/layout.tsx
src/components/common/Footer.tsx

황인정: [fix/#218] - 채팅방에서는 footer 안보이게 수정

---

src/app/meetingRoom/(lobby)/page.tsx
src/components/chat/chatHeader/ChatHeader.tsx
src/components/mainpage/MainBanner.tsx

황인정: [style/#218] - 메인 배너 글씨 크기 조절 + 채팅방 뒤로가기버튼 정렬 수정

---

src/components/room/lobby/LobbyBanner.tsx
src/components/room/lobby/MyRoomTitle.tsx
src/components/room/participants/HollowFemaleMemberCard.tsx
src/components/room/participants/HollowMaleMemberCard.tsx
src/components/room/participants/Member.tsx
src/components/room/singleMeetingRoom/RoomInformation.tsx
src/hooks/useMutation/useMeetingMutation.ts
src/hooks/useQueries/useMeetingQuery.ts
src/utils/icons/RoomAvatar.tsx

이혜진 -[fix] : 아바타 등 수정

---

src/app/layout.tsx
src/app/page.tsx
src/app/review/pageNumber/[pageNumber]/page.tsx
src/components/common/NavBarContents.tsx
src/components/mainpage/GetMostLikedReview.tsx
src/components/mainpage/MainBanner.tsx
src/components/mainpage/UseInformation.tsx
src/components/mypage/LikePost.tsx
src/components/mypage/MetPeople.tsx
src/components/mypage/MyPost.tsx
src/components/mypage/ProfileSetting.tsx
src/components/mypage/UserFavorite.tsx
src/components/review/ReviewCard.tsx
src/components/review/ReviewList.tsx
src/components/room/MemberNumberSelection.tsx
src/components/room/RegionSelection.tsx
src/components/room/lobby/LobbyBanner.tsx
src/components/room/lobby/MyRoomTitle.tsx
src/components/room/lobby/OtherRoomsTitle.tsx
src/components/room/participants/GotoChatButton.tsx
src/components/room/participants/Member.tsx
src/components/room/singleMeetingRoom/MeetingRoom.tsx
src/utils/banner/ThickBanner.tsx
src/utils/banner/ThinBanner.tsx

최희라 - [style] : merge 후 메인 및 마이페이지 스타일 수정

---

src/components/room/lobby/MeetingRoomList.tsx
src/components/room/lobby/MyRoomTitle.tsx
src/components/room/singleMeetingRoom/MeetingRoom.tsx

최희라 [style] : 미팅룸만 길이 변경

---

src/app/globals.css
src/app/meetingRoom/(lobby)/page.tsx
src/app/review/pageNumber/[pageNumber]/page.tsx
src/components/room/lobby/LobbyBanner.tsx
src/components/room/lobby/MeetingRoomList.tsx
src/components/room/lobby/ParticipatingRooms.tsx
src/components/room/singleMeetingRoom/MeetingRoom.tsx

황인정: [style/#218] - 로비 참여중 슬라이드 추가

---

src/app/review/[review_id]/page.tsx
src/app/review/layout.tsx
src/app/review/pageNumber/[pageNumber]/page.tsx
src/components/room/lobby/ParticipatingRooms.tsx
src/components/room/singleMeetingRoom/MeetingRoom.tsx

황인정: [fix/#218] - 리뷰페이지 배너

---

src/components/mypage/UserFavorite.tsx
src/components/mypage/UserKakaoId.tsx
src/components/mypage/UserNickname.tsx

최희라 - fix : 마이페이지 에러 수정

---

src/components/mypage/ProfileSetting.tsx
src/components/mypage/UserFavorite.tsx
src/components/mypage/UserGender.tsx

최희라 - [fix] : 마이페이지 빈값 유효성검사 추가

---

src/app/layout.tsx
src/components/chat/chatFooter/ChatInput.tsx
src/components/room/lobby/ParticipatingRooms.tsx
src/query/chat/chatQueryFns.ts

황인정: [fix/#218]

---

src/components/room/lobby/MeetingRoomList.tsx
src/components/room/lobby/ParticipatingRooms.tsx

최희라 - [style] : 미팅방 스타일 수정

---

src/components/chat/chatBody/ChatList.tsx
src/query/chat/chatQueryFns.ts

황인정: [fix/#218] - 채팅 시 공백 허용 불가 + 처음 채팅 시 오류 해결

---

src/utils/banner/ThinBanner.tsx

[style/#218] - 수정

---

src/app/chat/[chatroom_id]/page.tsx
src/components/chat/chatBody/ChatList.tsx
src/components/chat/chatBody/MyChat.tsx
src/components/chat/chatBody/OthersChat.tsx
src/components/chat/chatBody/ShowChatMember.tsx
src/components/chat/chatFooter/RememberLastChat.tsx
src/components/chat/chatHeader/ChatHeader.tsx
src/components/chat/chatHeader/InitChat.tsx
src/components/chat/sidebar/DateTimePicker.tsx
src/components/chat/sidebar/Map.tsx
src/components/chat/sidebar/SideBar.tsx
src/components/chat/sidebar/SideBarButton.tsx
src/components/common/NavBarContents.tsx
src/components/room/participants/GotoChatButton.tsx
src/hooks/useQueries/useChattingQuery.ts
src/query/chat/chatQueryFns.ts

황인정: [fix/#218] - 불필요한 서버요청 줄이기(성능개선)

---

src/app/chat/[chatroom_id]/page.tsx
src/components/chat/sidebar/SideBar.tsx

황인정: [style/#218] - sideBar.tsx 최소높이 설정

---

src/components/chat/chatBody/ChatList.tsx
src/components/chat/chatBody/MyChat.tsx
src/components/chat/chatBody/OthersChat.tsx
src/components/chat/chatBody/ShowChatMember.tsx
src/components/chat/chatFooter/RememberLastChat.tsx
src/components/chat/chatHeader/ChatHeader.tsx
src/components/chat/chatHeader/InitChat.tsx
src/components/chat/sidebar/DateTimePicker.tsx
src/components/chat/sidebar/Map.tsx
src/components/chat/sidebar/SideBar.tsx
src/components/room/InitRoom.tsx
src/hooks/useQueries/useChattingQuery.ts
src/query/chat/chatQueryFns.ts
src/query/meetingRoom/meetingQueryFns.ts
src/types/chatTypes.ts

황인정: [성능개선/#218] - 옵셔널 체이닝 줄이기 + join으로 불필요한 요청 줄이기

---

src/app/chat/layout.tsx

[fix/#218] - layout.tsx 없어도 ErrorBoundary 가능한지  실험중

---

src/app/chat/[chatroom_id]/page.tsx
src/app/chat/error.tsx
src/app/meetingRoom/(lobby)/page.tsx
src/app/meetingRoom/layout.tsx
src/hooks/useQueries/useChattingQuery.ts
src/query/chat/chatQueryFns.ts

황인정: [성능개선/#218] - ErrorBoundary

---

src/components/room/LobbySkeleton.tsx
src/components/room/MemberNumberSelection.tsx
src/components/room/RegionSelection.tsx
src/components/room/lobby/LobbyBanner.tsx
src/components/room/lobby/MeetingRoomForm.tsx
src/components/room/lobby/MeetingRoomList.tsx
src/components/room/lobby/MyRoomTitle.tsx
src/components/room/lobby/OtherRoomsTitle.tsx
src/components/room/lobby/ParticipatingRooms.tsx
src/components/room/lobby/RecruitingRooms.tsx
src/components/room/lobby/RefreshButton.tsx
src/components/room/participants/AcceptanceRoom.tsx
src/components/room/participants/GotoChatButton.tsx
src/components/room/participants/HollowFemaleMemberCard.tsx
src/components/room/participants/HollowMaleMemberCard.tsx
src/components/room/participants/Member.tsx
src/components/room/participants/RoomInformation.tsx
src/components/room/singleMeetingRoom/DeleteMeetingRoom.tsx
src/components/room/singleMeetingRoom/EditMeetingRoom.tsx
src/components/room/singleMeetingRoom/MeetingRoom.tsx
src/components/room/singleMeetingRoom/RoomInformation.tsx
src/hooks/useQueries/useMeetingQuery.ts
src/middleware.ts

```
export const useRoomInformationQuery = (roomId: string) => {
const [{ data: roomInfoWithId }, { data: roomMemberWithId }] = useSuspenseQueries({
queries: [
{
queryKey: [ROOMDATA, roomId],
queryFn: () => fetchRoomInfoWithRoomId(roomId),
select: (value: MeetingRoomType[]) => value[0]
},
{
queryKey: [ROOM_MEMBER, roomId],
queryFn: () => fetchRoomParticipants(roomId),
select: (value: ParticipantsWithId[]) => value.map((participant) => participant.users) as UserType[]
}
]
});
return { roomInfoWithId, roomMemberWithId };
};
```
```
```

이혜진 - [refactor]: 리엑트 쿼리 리펙토링(queries)

---

src/components/chat/chatBody/ChatList.tsx
src/components/chat/chatBody/LoadChatMore.tsx
src/components/chat/chatBody/OthersChat.tsx
src/components/chat/chatBody/ParticipantsInfoWrapper.tsx
src/query/meetingRoom/meetingQueryKeys.ts

count -> LoadCount로 변수명 변경
participants 자료구조 변경으로 인해 showThatUser()함수 사용도 변경
```
showThatUser(msg.send_from)?.avatar => showThatUser(msg.send_from).users.avatar
```
```
```

황인정: [fix] - 변수명 변경, 자료구조 변경으로 인한 오류 수정
